/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSmsRouteImport } from './routes/_authenticated/sms'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiTripsIndexRouteImport } from './routes/api/trips/index'
import { Route as ApiSmsMessagesIndexRouteImport } from './routes/api/sms-messages/index'
import { Route as ApiPassengersIndexRouteImport } from './routes/api/passengers/index'
import { Route as ApiExpensesIndexRouteImport } from './routes/api/expenses/index'
import { Route as ApiAnalyticsIndexRouteImport } from './routes/api/analytics/index'
import { Route as AuthenticatedTripsIndexRouteImport } from './routes/_authenticated/trips.index'
import { Route as ApiTripsTripIdRouteImport } from './routes/api/trips/$tripId'
import { Route as ApiPublicSmsRouteImport } from './routes/api/public/sms'
import { Route as ApiSmsMessagesSmsIdRouteImport } from './routes/api/sms-messages/$smsId'
import { Route as ApiPassengersPassengerIdRouteImport } from './routes/api/passengers/$passengerId'
import { Route as ApiExpensesExpenseIdRouteImport } from './routes/api/expenses/$expenseId'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthSignoutRouteImport } from './routes/api/auth/signout'
import { Route as ApiAuthSigninRouteImport } from './routes/api/auth/signin'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as AuthenticatedTripsTripIdRouteImport } from './routes/_authenticated/trips.$tripId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSmsRoute = AuthenticatedSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiTripsIndexRoute = ApiTripsIndexRouteImport.update({
  id: '/api/trips/',
  path: '/api/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmsMessagesIndexRoute = ApiSmsMessagesIndexRouteImport.update({
  id: '/api/sms-messages/',
  path: '/api/sms-messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPassengersIndexRoute = ApiPassengersIndexRouteImport.update({
  id: '/api/passengers/',
  path: '/api/passengers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpensesIndexRoute = ApiExpensesIndexRouteImport.update({
  id: '/api/expenses/',
  path: '/api/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsIndexRoute = ApiAnalyticsIndexRouteImport.update({
  id: '/api/analytics/',
  path: '/api/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTripsIndexRoute = AuthenticatedTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiTripsTripIdRoute = ApiTripsTripIdRouteImport.update({
  id: '/api/trips/$tripId',
  path: '/api/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSmsRoute = ApiPublicSmsRouteImport.update({
  id: '/api/public/sms',
  path: '/api/public/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmsMessagesSmsIdRoute = ApiSmsMessagesSmsIdRouteImport.update({
  id: '/api/sms-messages/$smsId',
  path: '/api/sms-messages/$smsId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPassengersPassengerIdRoute =
  ApiPassengersPassengerIdRouteImport.update({
    id: '/api/passengers/$passengerId',
    path: '/api/passengers/$passengerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExpensesExpenseIdRoute = ApiExpensesExpenseIdRouteImport.update({
  id: '/api/expenses/$expenseId',
  path: '/api/expenses/$expenseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignoutRoute = ApiAuthSignoutRouteImport.update({
  id: '/api/auth/signout',
  path: '/api/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSigninRoute = ApiAuthSigninRouteImport.update({
  id: '/api/auth/signin',
  path: '/api/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTripsTripIdRoute =
  AuthenticatedTripsTripIdRouteImport.update({
    id: '/trips/$tripId',
    path: '/trips/$tripId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/sms': typeof AuthenticatedSmsRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/expenses/$expenseId': typeof ApiExpensesExpenseIdRoute
  '/api/passengers/$passengerId': typeof ApiPassengersPassengerIdRoute
  '/api/sms-messages/$smsId': typeof ApiSmsMessagesSmsIdRoute
  '/api/public/sms': typeof ApiPublicSmsRoute
  '/api/trips/$tripId': typeof ApiTripsTripIdRoute
  '/trips/': typeof AuthenticatedTripsIndexRoute
  '/api/analytics/': typeof ApiAnalyticsIndexRoute
  '/api/expenses/': typeof ApiExpensesIndexRoute
  '/api/passengers/': typeof ApiPassengersIndexRoute
  '/api/sms-messages/': typeof ApiSmsMessagesIndexRoute
  '/api/trips/': typeof ApiTripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/sms': typeof AuthenticatedSmsRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/expenses/$expenseId': typeof ApiExpensesExpenseIdRoute
  '/api/passengers/$passengerId': typeof ApiPassengersPassengerIdRoute
  '/api/sms-messages/$smsId': typeof ApiSmsMessagesSmsIdRoute
  '/api/public/sms': typeof ApiPublicSmsRoute
  '/api/trips/$tripId': typeof ApiTripsTripIdRoute
  '/trips': typeof AuthenticatedTripsIndexRoute
  '/api/analytics': typeof ApiAnalyticsIndexRoute
  '/api/expenses': typeof ApiExpensesIndexRoute
  '/api/passengers': typeof ApiPassengersIndexRoute
  '/api/sms-messages': typeof ApiSmsMessagesIndexRoute
  '/api/trips': typeof ApiTripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/sms': typeof AuthenticatedSmsRoute
  '/_authenticated/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/expenses/$expenseId': typeof ApiExpensesExpenseIdRoute
  '/api/passengers/$passengerId': typeof ApiPassengersPassengerIdRoute
  '/api/sms-messages/$smsId': typeof ApiSmsMessagesSmsIdRoute
  '/api/public/sms': typeof ApiPublicSmsRoute
  '/api/trips/$tripId': typeof ApiTripsTripIdRoute
  '/_authenticated/trips/': typeof AuthenticatedTripsIndexRoute
  '/api/analytics/': typeof ApiAnalyticsIndexRoute
  '/api/expenses/': typeof ApiExpensesIndexRoute
  '/api/passengers/': typeof ApiPassengersIndexRoute
  '/api/sms-messages/': typeof ApiSmsMessagesIndexRoute
  '/api/trips/': typeof ApiTripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/expenses'
    | '/sms'
    | '/trips/$tripId'
    | '/api/auth/me'
    | '/api/auth/signin'
    | '/api/auth/signout'
    | '/api/auth/signup'
    | '/api/expenses/$expenseId'
    | '/api/passengers/$passengerId'
    | '/api/sms-messages/$smsId'
    | '/api/public/sms'
    | '/api/trips/$tripId'
    | '/trips/'
    | '/api/analytics/'
    | '/api/expenses/'
    | '/api/passengers/'
    | '/api/sms-messages/'
    | '/api/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/expenses'
    | '/sms'
    | '/trips/$tripId'
    | '/api/auth/me'
    | '/api/auth/signin'
    | '/api/auth/signout'
    | '/api/auth/signup'
    | '/api/expenses/$expenseId'
    | '/api/passengers/$passengerId'
    | '/api/sms-messages/$smsId'
    | '/api/public/sms'
    | '/api/trips/$tripId'
    | '/trips'
    | '/api/analytics'
    | '/api/expenses'
    | '/api/passengers'
    | '/api/sms-messages'
    | '/api/trips'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/sms'
    | '/_authenticated/trips/$tripId'
    | '/api/auth/me'
    | '/api/auth/signin'
    | '/api/auth/signout'
    | '/api/auth/signup'
    | '/api/expenses/$expenseId'
    | '/api/passengers/$passengerId'
    | '/api/sms-messages/$smsId'
    | '/api/public/sms'
    | '/api/trips/$tripId'
    | '/_authenticated/trips/'
    | '/api/analytics/'
    | '/api/expenses/'
    | '/api/passengers/'
    | '/api/sms-messages/'
    | '/api/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthSigninRoute: typeof ApiAuthSigninRoute
  ApiAuthSignoutRoute: typeof ApiAuthSignoutRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiExpensesExpenseIdRoute: typeof ApiExpensesExpenseIdRoute
  ApiPassengersPassengerIdRoute: typeof ApiPassengersPassengerIdRoute
  ApiSmsMessagesSmsIdRoute: typeof ApiSmsMessagesSmsIdRoute
  ApiPublicSmsRoute: typeof ApiPublicSmsRoute
  ApiTripsTripIdRoute: typeof ApiTripsTripIdRoute
  ApiAnalyticsIndexRoute: typeof ApiAnalyticsIndexRoute
  ApiExpensesIndexRoute: typeof ApiExpensesIndexRoute
  ApiPassengersIndexRoute: typeof ApiPassengersIndexRoute
  ApiSmsMessagesIndexRoute: typeof ApiSmsMessagesIndexRoute
  ApiTripsIndexRoute: typeof ApiTripsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/sms-messages/$smsId': {
      id: '/api/sms-messages/$smsId'
      path: '/api/sms-messages/$smsId'
      fullPath: '/api/sms-messages/$smsId'
      preLoaderRoute: typeof ApiSmsMessagesSmsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sms': {
      id: '/_authenticated/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof AuthenticatedSmsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/trips/': {
      id: '/api/trips/'
      path: '/api/trips'
      fullPath: '/api/trips/'
      preLoaderRoute: typeof ApiTripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sms-messages/': {
      id: '/api/sms-messages/'
      path: '/api/sms-messages'
      fullPath: '/api/sms-messages/'
      preLoaderRoute: typeof ApiSmsMessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/passengers/': {
      id: '/api/passengers/'
      path: '/api/passengers'
      fullPath: '/api/passengers/'
      preLoaderRoute: typeof ApiPassengersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expenses/': {
      id: '/api/expenses/'
      path: '/api/expenses'
      fullPath: '/api/expenses/'
      preLoaderRoute: typeof ApiExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/': {
      id: '/api/analytics/'
      path: '/api/analytics'
      fullPath: '/api/analytics/'
      preLoaderRoute: typeof ApiAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trips/': {
      id: '/_authenticated/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof AuthenticatedTripsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/trips/$tripId': {
      id: '/api/trips/$tripId'
      path: '/api/trips/$tripId'
      fullPath: '/api/trips/$tripId'
      preLoaderRoute: typeof ApiTripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sms': {
      id: '/api/public/sms'
      path: '/api/public/sms'
      fullPath: '/api/public/sms'
      preLoaderRoute: typeof ApiPublicSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/passengers/$passengerId': {
      id: '/api/passengers/$passengerId'
      path: '/api/passengers/$passengerId'
      fullPath: '/api/passengers/$passengerId'
      preLoaderRoute: typeof ApiPassengersPassengerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expenses/$expenseId': {
      id: '/api/expenses/$expenseId'
      path: '/api/expenses/$expenseId'
      fullPath: '/api/expenses/$expenseId'
      preLoaderRoute: typeof ApiExpensesExpenseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signout': {
      id: '/api/auth/signout'
      path: '/api/auth/signout'
      fullPath: '/api/auth/signout'
      preLoaderRoute: typeof ApiAuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signin': {
      id: '/api/auth/signin'
      path: '/api/auth/signin'
      fullPath: '/api/auth/signin'
      preLoaderRoute: typeof ApiAuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trips/$tripId': {
      id: '/_authenticated/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AuthenticatedTripsTripIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedSmsRoute: typeof AuthenticatedSmsRoute
  AuthenticatedTripsTripIdRoute: typeof AuthenticatedTripsTripIdRoute
  AuthenticatedTripsIndexRoute: typeof AuthenticatedTripsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedSmsRoute: AuthenticatedSmsRoute,
  AuthenticatedTripsTripIdRoute: AuthenticatedTripsTripIdRoute,
  AuthenticatedTripsIndexRoute: AuthenticatedTripsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthSigninRoute: ApiAuthSigninRoute,
  ApiAuthSignoutRoute: ApiAuthSignoutRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiExpensesExpenseIdRoute: ApiExpensesExpenseIdRoute,
  ApiPassengersPassengerIdRoute: ApiPassengersPassengerIdRoute,
  ApiSmsMessagesSmsIdRoute: ApiSmsMessagesSmsIdRoute,
  ApiPublicSmsRoute: ApiPublicSmsRoute,
  ApiTripsTripIdRoute: ApiTripsTripIdRoute,
  ApiAnalyticsIndexRoute: ApiAnalyticsIndexRoute,
  ApiExpensesIndexRoute: ApiExpensesIndexRoute,
  ApiPassengersIndexRoute: ApiPassengersIndexRoute,
  ApiSmsMessagesIndexRoute: ApiSmsMessagesIndexRoute,
  ApiTripsIndexRoute: ApiTripsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
